


# when you use "user defined" / random names - values at that time we can able to view warnings:
#  to avoid that we need to create one file that is in "pytest.ini" file. format

[pytest]
markers=
    sanity
    regression
    one
    two
    three